// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWK8ZodxFtAxmmb1A8oU49cGknYIy5DkI',
    appId: '1:90739095884:web:b66b3dbe1b3ff4758f77e9',
    messagingSenderId: '90739095884',
    projectId: 'mynotes-flutter-tutorial-123',
    authDomain: 'mynotes-flutter-tutorial-123.firebaseapp.com',
    storageBucket: 'mynotes-flutter-tutorial-123.appspot.com',
    measurementId: 'G-ECK0YJ25VJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsMUSJ4NuYbcPXNnH69WVuIlaLF5l04Yo',
    appId: '1:90739095884:android:bed0bd9b302eac5f8f77e9',
    messagingSenderId: '90739095884',
    projectId: 'mynotes-flutter-tutorial-123',
    storageBucket: 'mynotes-flutter-tutorial-123.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1hYrF60BBWnP_JKyDac6weLozzrC2T5Y',
    appId: '1:90739095884:ios:01f138b03bb143918f77e9',
    messagingSenderId: '90739095884',
    projectId: 'mynotes-flutter-tutorial-123',
    storageBucket: 'mynotes-flutter-tutorial-123.appspot.com',
    iosClientId: '90739095884-sg5hgemdckuvg40tg5svg5tkvgevulff.apps.googleusercontent.com',
    iosBundleId: 'com.random-domain.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1hYrF60BBWnP_JKyDac6weLozzrC2T5Y',
    appId: '1:90739095884:ios:01f138b03bb143918f77e9',
    messagingSenderId: '90739095884',
    projectId: 'mynotes-flutter-tutorial-123',
    storageBucket: 'mynotes-flutter-tutorial-123.appspot.com',
    iosClientId: '90739095884-sg5hgemdckuvg40tg5svg5tkvgevulff.apps.googleusercontent.com',
    iosBundleId: 'com.random-domain.mynotes',
  );
}
